language: node_js
node_js:
  - "10"

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
    - ipetrbroz@gmail.com
    on_success: change
    on_failure: always
